#!/bin/bash

#Pesquise pelas expressions abaixo e configure corretamente .
#...Observe que uma mesma expression pode aparecer diversas vezes durante o codigo .
##MYSQL_PASSWORD
###Para configurar a senha do mysql
##REPOSITORY
##VERSION

#Aplique 'chmod 755' a esse arquivo antes de tentar executa-lo

#O banco de dados de 'production' deve ser o public
#O banco de dados de 'development' deve ser o dev

sudo apt update

sudo apt install apache2
sudo apt install php
sudo apt install wget
sudo apt install git

sudo apt install php-mysqli php-mbstring php-xml php-zip

#laravel

echo '
;Configs ProXWeb
extension=mbstring
extension=openssl
extension=pdo_mysql
' >> /etc/php/7.3/apache2/php.ini

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

php composer-setup.php

sudo mv composer.phar /usr/local/bin/composer

composer global require "laravel/installer"

sudo cp -r .config/composer/vendor/ /usr/bin/vendor/

sudo mv /usr/bin/vendor/bin/laravel /usr/bin/laravel

wget http://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb

sudo apt install ./mysql-apt-config_0.8.13-1_all.deb

sudo apt update

#esse install tem que ser obrigatoriamente após os passos anteriores
sudo apt install mysql-server

sudo mysql_secure_installation

#phpmyadmin
wget https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.tar.gz

tar xvf phpMyAdmin-4.9.0.1-all-languages.tar.gz

sudo mv phpMyAdmin-4.9.0.1-all-languages /usr/share/phpmyadmin

//temp foler dedicated
sudo mkdir -p /var/lib/phpmyadmin/tmp

//cache?
sudo chown -R www-data:www-data /var/lib/phpmyadmin

sudo mkdir /etc/phpmyadmin/

sudo cp /usr/share/phpmyadmin/config.sample.inc.php  /usr/share/phpmyadmin/config.inc.php

echo '
/*Configs ProXWeb*/
$cfg['blowfish_secret'] = 'root';
$cfg['TempDir'] = '/var/lib/phpmyadmin/tmp';
' >> /usr/share/phpmyadmin/config.inc.php

echo '
Alias /Hercules /usr/share/phpmyadmin

<Directory /usr/share/phpmyadmin>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.php

    <IfModule mod_php5.c>
        <IfModule mod_mime.c>
            AddType application/x-httpd-php .php
        </IfModule>
        <FilesMatch ".+\.php$">
            SetHandler application/x-httpd-php
        </FilesMatch>

        php_value include_path .
        php_admin_value upload_tmp_dir /var/lib/phpmyadmin/tmp
        php_admin_value open_basedir /usr/share/phpmyadmin/:/etc/phpmyadmin/:/var/lib/phpmyadmin/:/usr/share/php/php-gettext/:/usr/share/php/php-php-gettext/:/usr/share/javascript/:/usr/share/php/tcpdf/:/usr/share/doc/phpmyadmin/:/usr/share/php/phpseclib/
        php_admin_value mbstring.func_overload 0
    </IfModule>
    <IfModule mod_php.c>
        <IfModule mod_mime.c>
            AddType application/x-httpd-php .php
        </IfModule>
        <FilesMatch ".+\.php$">
            SetHandler application/x-httpd-php
        </FilesMatch>

        php_value include_path .
        php_admin_value upload_tmp_dir /var/lib/phpmyadmin/tmp
        php_admin_value open_basedir /usr/share/phpmyadmin/:/etc/phpmyadmin/:/var/lib/phpmyadmin/:/usr/share/php/php-gettext/:/usr/share/php/php-php-gettext/:/usr/share/javascript/:/usr/share/php/tcpdf/:/usr/share/doc/phpmyadmin/:/usr/share/php/phpseclib/
        php_admin_value mbstring.func_overload 0
    </IfModule>

</Directory>

<Directory /usr/share/phpmyadmin/setup>
    <IfModule mod_authz_core.c>
        <IfModule mod_authn_file.c>
            AuthType Basic
            AuthName "phpMyAdmin Setup"
            AuthUserFile /etc/phpmyadmin/htpasswd.setup
        </IfModule>
        Require valid-user
    </IfModule>
</Directory>


<Directory /usr/share/phpmyadmin/templates>
    Require all denied
</Directory>
<Directory /usr/share/phpmyadmin/libraries>
    Require all denied
</Directory>
<Directory /usr/share/phpmyadmin/setup/lib>
    Require all denied
</Directory>
' >> /etc/apache2/conf-enabled/phpmyadmin.conf

sudo a2enmod rewrite

#armazenar as credenciais ao invés de ficar pedindo toda vez
git config credential.helper store

sudo git clone REPOSITORY /var/www/html/VERSION/

sudo mv /var/www/html/index.html /var/www/html/2index.html

echo '
<?php

	header("Location: app");
	
 ?>
' >> /var/www/html/index.php

echo '
APP_NAME=ProXWeb
APP_ENV=local
APP_KEY=base64:b0HSwsIOyD5wXKC3XKVUSKCEosz61Gf6pHQMyXBNT2Q=
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=public
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
' >> /var/www/html/VERSION/.env

sudo chmod -R 777 /var/www/html/VERSION/storage

sudo chmod -R 777 /var/www/html/VERSION/bootstrap/cache

#PROVAVELMENTE NÃO PRECISA EXECUTAR
#chown -R www-data.www-data /var/www/html/VERSION

#COMMENT DA PRIMEIRA IMPLEMENTACION
#CONTINUAR A PARTIR DAQUI

echo '


<Directory "/var/www/html/">
	Allowoverride All
</Directory>
' >> /etc/apache2/apache2.conf

php /var/www/html/VERSION/artisan config:cache

php /var/www/html/VERSION/artisan route:cache

sudo git clone REPOSITORY /var/www/html/development/

echo '
APP_NAME=ProXWeb
APP_ENV=local
APP_KEY=base64:b0HSwsIOyD5wXKC3XKVUSKCEosz61Gf6pHQMyXBNT2Q=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=dev
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
' >> /var/www/html/development/.env

sudo chmod -R 777 /var/www/html/development/storage

sudo chmod -R 777 /var/www/html/development/bootstrap/cache

#PROVAVELMENTE NÃO PRECISA EXECUTAR
#chown -R www-data.www-data /var/www/html/development

#ESTAH COM ERRO NESSE PASSO POR ISSO SERA FEITO POR LINKS E NOT POR ALIASES
#echo '
#Alias /app /var/www/html/v1.0/public
#' > /etc/apache2/conf-enabled/app.conf

#echo '
#Alias /dev /var/www/html/development/public
#' > /etc/apache2/conf-enabled/dev.conf

ln -s /var/www/html/VERSION/public /var/www/html/app

ln -s /var/www/html/development/public /var/www/html/dev

sudo /etc/init.d/apache2 restart

#[configure your web server's document / web root to be the public directory LARAVEL]->Bing